version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: w1-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: w1project
      POSTGRES_DB: w1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - w1-network

volumes:
  postgres_data:
    driver: local

networks:
  w1-network:
    external: true